swagger:
    base:
        package: com.mergenie.apiaggregate
    developer:
        name: Ayhan Ugurlu
eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: false
        register-with-eureka: true
    dashboard:
        enabled: true
server:
    port: 8761
spring:
    application:
        name: discovery-server
